# -*- coding: utf-8 -*-
__author__ = 'Administrator'

#REDIS
REDIS_SERVER = "127.0.0.1"
REDIS_PORT = 6379
REDIS_PW=''

#MYSQL
MYSQL_SERVER = "127.0.0.1"
MYSQL_PORT = 3307
MYSQL_USER='root'
MYSQL_PW='root'
MYSQL_CHARSET='utf8'
MYSQL_DB='iso100'

DUPLICATE_SOURCE='MYSQL' #REDIS or MYSQL
DUPLICATE_FIELD='imageurl'

RESPONSE_ENCODING='gbk'

CRAWLER_NUM=30
COLLECTOR_NUM=10

SLAVE_CRAWLER_NUM=15
SLAVE_COLLECTOR_NUM=40

REDIS_PAGEQUEUE_1='pagequeue1'
REDIS_PAGEQUEUE_2='pagequeue2'

REDIS_TASKQUEUE='REDIS_TASKQUEUE'
REDIS_TASKQUEUE_SAVEFREQUENCY=10
REDIS_TASK_CURRENT='REDIS_TASK_CURRENT'

REDIS_CRAWLERQUEUE_1='REDIS_CRAWLERQUEUE_1'
REDIS_CRAWLERQUEUE_2='REDIS_CRAWLERQUEUE_2'

REDIS_COLLECTORQUEUE_1='REDIS_COLLECTORQUEUE_1'
REDIS_COLLECTORQUEUE_2='REDIS_COLLECTORQUEUE_2'

REDIS_RESULTQUEUE_1='REDIS_RESULTQUEUE_1'

#start_urls=('http://url1','http://url1')
start_urls='http://www.gettyimages.cn/page/icindex.html'



