# -*- coding: utf-8 -*-
__author__ = 'Administrator'

#REDIS
REDIS_SERVER = "127.0.0.1"
REDIS_PORT = 6379
REDIS_PW=''

CRAWLER_NUM=15
COLLECTOR_NUM=40

SLAVE_CRAWLER_NUM=15
SLAVE_COLLECTOR_NUM=40

REDIS_PAGEQUEUE_1='pagequeue1'
REDIS_PAGEQUEUE_2='pagequeue2'

REDIS_TASK_QUEUE='task'

REDIS_CRAWLERQUEUE_1='REDIS_CRAWLERQUEUE_1'
REDIS_CRAWLERQUEUE_2='REDIS_CRAWLERQUEUE_2'

REDIS_COLLECTORQUEUE_1='REDIS_COLLECTORQUEUE_1'
REDIS_COLLECTORQUEUE_2='REDIS_COLLECTORQUEUE_2'

REDIS_RESULTQUEUE_1='REDIS_RESULTQUEUE_1'

#start_urls=('http://url1','http://url1')
start_urls='http://www.gettyimages.cn/page/icindex.html'



